spring.application.name=employeeManagementSystem
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/employee?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# The URI of the authorization server's issuer. This is the base URL of the Keycloak realm.
# It helps to verify the authenticity of the JWT by ensuring it comes from a trusted source.
spring.security.oauth2.resourceserver.jwt.issuer-uri = http://localhost:8080/realms/project

